### ISSUE TITLE
در خواست فعال سازی گیت ‌‌‌هاب پیجس

### ISSUE THREAD

**Issue by mmdbalkhi** [Hossein52Hz/The-Art-Of-Readable-Code-Persian#1]
<div dir="rtl">
سلام خسته نباشید بسیار کار خوب و باحالی کردید ممنون از شما ترجمه هم خیلی تمیزه عالیه ولی بهتره که گیت‌هاب پیج رو فعال کنید چون مطالعه اون راحتر نسبت به این هستش

میتونید از لینک زیر هم اقدام کنید

https://github.com/Hossein52Hz/The-Art-Of-Readable-Code-Persian/settings/pages

**Comment by Hossein52Hz** [comment]
<div dir="rtl">
سلام Komeil جان  وقتت بخیر
خواهش میکنم.
با اینکه فایل های مربوط به هر فصل بصورت مارک‌دان هست ولی مشکل نمایش وجود دارد.
لینک های تصاویر هم فکر میکنم باید تغییر کنند که یکمی آماده سازی این موارد زمان میبره و اولویت فعلی آماده سازی فصل های تکمیل نشده است.
ولی حتما پس از اتمام فصل ها روی jekyll یا mkdocs اوکی میکنم که مرتب باشه.
</div>

**Comment by mmdbalkhi** [comment]
سلام ممنون بابت پاسخگویی شما اگر موافق باشید این کار ها رو من بکنم و به شما زحمت ندم 
و اینکه فصل ها رو از پی دی اف تایپ میکنید درسته؟ اگر بله تو اینجا هم اگر مایل باشید در کد توانم کمک میکنم ولی فکر کنم pandoc بتونه پی دی آف رو تبدیل به مارک داون بکنه

**Comment by Hossein52Hz** [comment]
<div dir='rtl'>
مرسی کمیل جان
خوشحال میشم از کمکت استفاده کنم.
 خوشبختانه قبلا تایپ کردم :) صرفا بصورت فایل های مارک دان تنظیم میکنم و ...
در مورد گیت‌هاب پیج هم اگر عجله ای نداری بعد از تکمیل شدن فصل ها ازت کمک میگیرم حتما.

اگر هم تمایل داری که توی آماده سازی فایل های مارک دان کمک کنی یک ایمیل بهم بزن تا با همدیگه هماهنگ بشیم.
همچنین برخی از فصل ها فوت نوت‌هاشون تکمیل نشده.

hossein52hz@gmail.com
</div>

**Comment by mmdbalkhi** [comment]
سلام آقا حسین ممنون بابت ادغام فصل بعدی رو هم می‌فرستم ان‌شاءالله تا چند روز دیگه :)

**Comment by Hossein52Hz** [comment]
سلام کمیل جان
خواهش میکنم ممنون بابت کمکت.
فقط برای فصل جدید شماره فصل و لینک‌های تصاویر را طبق الگوی فصل های دیگه بزار.
بازم مرسی

**Comment by mmdbalkhi** [comment]
<div dir="rtl">
چشم فقط منظورتون اینه که در div راست چین نباشه ؟
فقط شماره فصل رو متوجه نشدم یعنی چطور ؟ چون شماره فصل ها و اسم فایل ها دقیقا اون چیزیه که شما فرستادید و من اصلا با اونا کاری نداشتم
</div>

**Comment by Hossein52Hz** [comment]
فقط فصل ۱۰ باقی مونده.
شما فصل ۱۰ را طبق همون روال قبلی  انجام بده.
بقیه فصل ها اسم و لینک هاشون بروز شدن. 
مرسی

**Comment by mmdbalkhi** [comment]
سلام آقا حسین خیلی ممنون بابت مرج 
بنظرم دیگه به این ایشو نیازی نیست پس با اجازه شما میبندمش و اگر باز کمکی یا کاری نیاز بود حتما ایمیل بزنید تمام سعیم رو میکنم 
کمکتون کنم
ahmdparsh129@gmail.com
